version: '3'
services:
  redis:
    image: redis
    ports:
      - "6380:6380"
  web:
    # COMPLETE HERE
    image: app-container
    build: .
    ports:
      - "5000:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6380
    restart: on-failure
    depends_on:
      - redis
    links:
      - redis 
    volumes:
      - myvolume:/data
volumes:
  myvolume:  
