apiVersion: apps/v1 
kind: Deployment
metadata:
  name: project-devops
  labels:
    app: project-devops
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-devops
      version: v1
  template:
    metadata:
      labels:
        app: project-devops
        version: v1
    spec:
      containers:
        - name: project-devops
          image: redseahorse/projet-devops-test
          ports:
            - containerPort: 3000
              protocol: TCP

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: project-devops
  labels:
    app: project-devops
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-devops
      version: v2
  template:
    metadata:
      labels:
        app: project-devops
        version: v2
    spec:
      containers:
        - name: project-devops
          image: redseahorse/projet-devops-testv2
          ports:
            - containerPort: 3000
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: project-devops
spec:
  selector:
    app: project-devops
  ports:
    - name: http
      port: 3000   
      
---     
apiVersion: v1
kind: ServiceAccount
metadata:
  name: project-devops
  labels:
    account: project-devops
    
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  labels:
    account: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdep
  labels:
    app: redisdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisdep
  template:
    metadata:
      labels:
        app: redisdep
    spec:
      volumes:
        - name: vol-dev
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /redisData
              name: vol-dev
---
apiVersion: v1
kind: Service
metadata:
  name: rediserv
spec:
  selector:
    app: redisdep
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi          
