apiVersion: apps/v1 
kind: Deployment
metadata:
  name: project-devops
  labels:
    app: project-devops
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-devops
  template:
    metadata:
      labels:
        app: project-devops
        version: v1
    spec:
      containers:
        - name: project-devops
          image: redseahorse/projet-devops-test
          ports:
            - containerPort: 3000
              protocol: TCP

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: project-devops-v2
  labels:
    app: project-devops
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-devops
  template:
    metadata:
      labels:
        app: project-devops
        version: v2
    spec:
      containers:
        - name: project-devops
          image: redseahorse/projet-devops-testv2
          ports:
            - containerPort: 3000
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: project-devops-service-v1
spec:
  selector:
    app: project-devops
  ports:
    - name: http
      port: 3000
      
---
apiVersion: v1
kind: Service
metadata:
  name: project-devops-service-v2
spec:
  selector:
    app: project-devops
  ports:
    - name: http
      port: 3000   
