apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: devops-destination
  namespace: my-app
spec:
  host: project-devops-deployment
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
