apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: devops-gateway
  namespace: my-app
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: http
      protocol: HTTP
    hosts:
    - "*"
