apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: project-devops-deployment
  namespace: my-app
spec:
  hosts:
  - "*"
  gateways:
  - devops-gateway
  http:
  - route:
    - destination:
        subset: v1
        host: project-devops-deployment
        port:
          number: 443
      weight: 50
    - destination:
        subset: v2
        host: project-devops-deployment
        port:
          number: 443
      weight: 50
